# Generated by Django 4.2.7 on 2023-12-23 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0003_alter_surveyquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyquestion',
            options={'ordering': ['-order']},
        ),
        migrations.AlterModelOptions(
            name='surveytemplate',
            options={'ordering': ['-order']},
        ),
    ]
