# Generated by Django 4.2.7 on 2023-12-23 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0005_surveyconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyconfig',
            options={'verbose_name': 'Survey Config'},
        ),
    ]
