# Generated by Django 4.2.7 on 2023-12-23 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0006_alter_surveyconfig_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pr.surveyconfig')),
            ],
            options={
                'ordering': ['-order'],
            },
        ),
    ]
