# Generated by Django 4.2.9 on 2024-02-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0007_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyconfig',
            options={'verbose_name': 'Survey Whatsapp Message Config'},
        ),
        migrations.AlterField(
            model_name='surveytemplate',
            name='flag',
            field=models.BooleanField(unique=True, verbose_name='out patient'),
        ),
    ]
