# Generated by Django 4.2.9 on 2024-02-10 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0008_alter_surveyconfig_options_alter_surveytemplate_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyinfo',
            old_name='admission_no',
            new_name='medical_no',
        ),
    ]
