# Generated by Django 4.2.7 on 2024-02-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0011_rename_medical_no_surveyinfo_admission_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyinfo',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='surveyinfo',
            name='satisfied',
        ),
        migrations.AddField(
            model_name='survey',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='satisfied',
            field=models.BooleanField(default=True),
        ),
    ]
