# Generated by Django 4.2.7 on 2024-02-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0012_remove_surveyinfo_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyanswer',
            name='category',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nursing', 'Nursing'), ('receptionist', 'Receptionist'), ('security', 'Security'), ('kitchen', 'Kitchen'), ('care', 'Care')], default='doctor', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='weight',
            field=models.PositiveIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='category',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nursing', 'Nursing'), ('receptionist', 'Receptionist'), ('security', 'Security'), ('kitchen', 'Kitchen'), ('care', 'Care')], default='doctor', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='weight',
            field=models.PositiveIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1),
        ),
    ]
