# Generated by Django 4.2.7 on 2024-02-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0013_surveyanswer_category_surveyanswer_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyanswer',
            name='weight',
            field=models.PositiveIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1, verbose_name='periority'),
        ),
    ]
