# Generated by Django 4.2.7 on 2024-02-18 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0014_alter_surveyanswer_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyanswer',
            old_name='weight',
            new_name='periority',
        ),
    ]
