# Generated by Django 4.2.7 on 2024-02-18 06:41

from django.db import migrations

def convert_answers(apps, schema_editor):
    Answer = apps.get_model('pr', 'SurveyAnswer')
    for answer in Answer.objects.all():
        if answer.answer == 'yes':
            answer.answer = '1'
        elif answer.answer == 'no':
            answer.answer = '0'
        answer.save()
        
class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0016_remove_surveyquestion_weight_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_answers)
    ]
