# Generated by Django 4.2.7 on 2024-03-07 05:10

from django.db import migrations

def update_groups(apps, schema_editor):
    SurveyAnswer = apps.get_model('pr', 'SurveyAnswer')
    SurveyAnswer.objects.filter(category='doctor').update(category='medical')
    SurveyAnswer.objects.filter(category='receptionist').update(category='admission_office')
    SurveyAnswer.objects.filter(category='kitchen').update(category='food_and_beverages')
    SurveyAnswer.objects.filter(category='care').update(category='hospitality')


    
class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0020_alter_surveyanswer_category_and_more'),
    ]

    operations = [
        migrations.RunPython(update_groups),
    ]
