# Generated by Django 4.2.7 on 2024-03-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0022_survey_questions_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyanswer',
            name='category',
            field=models.CharField(choices=[('medical', 'Medical'), ('nursing', 'Nursing'), ('admission_office', 'Admission Office'), ('security', 'Security'), ('food_and_beverages', 'Food & Beverages'), ('hospitality', 'Hospitality'), ('recommendation', 'Recommendation')], max_length=50),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='category',
            field=models.CharField(choices=[('medical', 'Medical'), ('nursing', 'Nursing'), ('admission_office', 'Admission Office'), ('security', 'Security'), ('food_and_beverages', 'Food & Beverages'), ('hospitality', 'Hospitality'), ('recommendation', 'Recommendation')], max_length=50),
        ),
    ]
