# Generated by Django 4.2.7 on 2023-11-11 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_commenter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_comment', to='ticket.ticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_department', to='users.department'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='issuetype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_issue', to='ticket.issuestype'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='ticket_subscribers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notemedia',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_note', to='ticket.note'),
        ),
        migrations.AddField(
            model_name='notecomment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_commenter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notecomment',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_note', to='ticket.note'),
        ),
        migrations.AddField(
            model_name='note',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='note_department', to='users.department'),
        ),
        migrations.AddField(
            model_name='note',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_poster', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issuestype',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='department_issue', to='users.department'),
        ),
        migrations.AddField(
            model_name='importexportfile',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_in_department', to='users.department'),
        ),
        migrations.AddField(
            model_name='importexportfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_for_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='complaint',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.department'),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='issuetype',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ticket.issuestype'),
        ),
    ]
