# Generated by Django 4.2.7 on 2023-11-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_historicalticket_building_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='building',
            field=models.CharField(choices=[('building_1', 'Building 1'), ('building_2', 'Building 2'), ('stores', 'Stores')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='building',
            field=models.CharField(choices=[('building_1', 'Building 1'), ('building_2', 'Building 2'), ('stores', 'Stores')], max_length=10),
        ),
    ]
