# Generated by Django 4.2.7 on 2024-07-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_rename_discribtion_historicalticket_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
