# Generated by Django 5.0.6 on 2024-07-26 11:05

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_historicalticket_is_external_historicalticket_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='closed_at'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='closed_at'),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='resolution_time',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('closed_at'), '-', models.F('created_at')), output_field=models.DurationField()),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolution_time',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('closed_at'), '-', models.F('created_at')), output_field=models.DurationField()),
        ),
    ]
