# Generated by Django 5.0.9 on 2026-07-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_department_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='sla_hours',
            field=models.PositiveIntegerField(default=24, help_text='Base hours allowed to resolve a ticket in this department.', verbose_name='SLA hours'),
        ),
    ]
