# Generated by Django 5.0.9 on 2026-07-28 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_department_sla_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeptPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_receive_tickets', models.BooleanField(default=True)),
                ('can_send_tickets', models.BooleanField(default=True)),
                ('can_view_all_dept_tickets', models.BooleanField(default=True)),
                ('can_assign_tickets', models.BooleanField(default=True)),
                ('can_change_status', models.BooleanField(default=True)),
                ('can_transfer_tickets', models.BooleanField(default=True)),
                ('can_archive_tickets', models.BooleanField(default=False)),
                ('can_export_data', models.BooleanField(default=False)),
                ('can_view_analytics', models.BooleanField(default=False)),
                ('can_manage_team_notes', models.BooleanField(default=True)),
                ('can_manage_dept_users', models.BooleanField(default=False)),
                ('can_view_audit_logs', models.BooleanField(default=False)),
                ('can_manage_knowledge_base', models.BooleanField(default=False)),
                ('can_manage_assets', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'department permissions',
                'verbose_name_plural': 'department permissions',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='default_permissions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='users.deptpermissions'),
        ),
        migrations.CreateModel(
            name='UserPermissionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_receive_tickets', models.BooleanField(blank=True, null=True)),
                ('can_send_tickets', models.BooleanField(blank=True, null=True)),
                ('can_view_all_dept_tickets', models.BooleanField(blank=True, null=True)),
                ('can_assign_tickets', models.BooleanField(blank=True, null=True)),
                ('can_change_status', models.BooleanField(blank=True, null=True)),
                ('can_transfer_tickets', models.BooleanField(blank=True, null=True)),
                ('can_archive_tickets', models.BooleanField(blank=True, null=True)),
                ('can_export_data', models.BooleanField(blank=True, null=True)),
                ('can_view_analytics', models.BooleanField(blank=True, null=True)),
                ('can_manage_team_notes', models.BooleanField(blank=True, null=True)),
                ('can_manage_dept_users', models.BooleanField(blank=True, null=True)),
                ('can_view_audit_logs', models.BooleanField(blank=True, null=True)),
                ('can_manage_knowledge_base', models.BooleanField(blank=True, null=True)),
                ('can_manage_assets', models.BooleanField(blank=True, null=True)),
                ('allowed_transfer_dept_ids', models.JSONField(blank=True, default=list, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permission_override', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user permission override',
                'verbose_name_plural': 'user permission overrides',
            },
        ),
    ]
