# Generated by Django 4.2.7 on 2023-12-12 19:00

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='modules',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(choices=[('ticket', 'Ticket'), ('pr', 'PR')], max_length=50), blank=True, null=True, size=None),
        ),
    ]
