"""
Django settings for ABCHospital project.

Generated by 'django-admin startproject' using Django 3.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
import sys
import firebase_admin
from pathlib import Path
from django.utils.translation import gettext_lazy as _
import socket


# Firebase push notifications. The service-account file holds a private key and
# is deliberately not in version control, so a fresh checkout will not have it —
# start without push rather than refusing to boot. Point
# FIREBASE_CREDENTIALS at the file on a server that needs notifications.
_firebase_cred_path = os.environ.get('FIREBASE_CREDENTIALS', './ticketingcrm.json')
if os.path.exists(_firebase_cred_path):
    cred = firebase_admin.credentials.Certificate(_firebase_cred_path)
    firebase_admin.initialize_app(cred)
else:
    import warnings
    warnings.warn(
        f"Firebase credentials not found at {_firebase_cred_path}; "
        "push notifications are disabled."
    )

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read from the environment. The key was previously hardcoded here, which means
# it shipped to anyone who could read the source — and this key signs sessions
# and password-reset tokens. Set DJANGO_SECRET_KEY on the server; the fallback
# below exists only so a developer checkout still boots.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-local-development-only-do-not-use-in-production',
)

ip = (([ip for ip in socket.gethostbyname_ex(socket.gethostname())[2] if not ip.startswith("127.")] or [[(s.connect(
    ("8.8.8.8", 53)), s.getsockname()[0], s.close()) for s in [socket.socket(socket.AF_INET, socket.SOCK_DGRAM)]][0][1]]) + ["null"])[0]

IP = ip if not ip == "null" else "127.0.0.1"
LOCAL_IP = '10.10.1.40'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition
MAIN_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

INTERNAL_APPS = [
    'users',
    'ticket',
    "pr",
    "dashboard",
    "catalog",
]

THIRD_PARTY_APPS = [
    'corsheaders', 'storages', 'simple_history',
    'fcm_django',
    "django_extensions",
    'django_async_orm', 'channels',
    'rest_framework', 'rest_framework.authtoken',  # new!
    'rest_framework_swagger', 'drf_yasg',
    "django_better_admin_arrayfield",
    "django_filters",
    "solo",
    "adminsortable2",

]


INSTALLED_APPS = MAIN_APPS + INTERNAL_APPS + THIRD_PARTY_APPS


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.cache.UpdateCacheMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # new
    'corsheaders.middleware.CorsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'ABCHospital.middlewares.RequestMiddleware',
    # Binds the request to the thread so audit signals know who is acting.
    'catalog.audit.AuditContextMiddleware',
]

ROOT_URLCONF = 'ABCHospital.urls'
# If this is used then `CORS_ORIGIN_WHITELIST` will not have any effect
CORS_ORIGIN_ALLOW_ALL = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'ABCHospital.asgi.application'


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': f'redis://{LOCAL_IP}:6379',
    }
}

# # Database
# # https://docs.djangoproject.com/en/3.2/ref/settings/#databases
# Database
# # https://docs.djangoproject.com/en/3.2/ref/settings/#databases
# Credentials come from the environment. They used to be literals here, so the
# database password travelled with every copy of the source.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'USER': os.environ.get('DJANGO_DB_USER', 'abc'),
        'NAME': os.environ.get('DJANGO_DB_NAME', 'abc'),
        'PASSWORD': os.environ.get('DJANGO_DB_PASSWORD', ''),
        'HOST': os.environ.get('DJANGO_DB_HOST', LOCAL_IP),
        'PORT': os.environ.get('DJANGO_DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_USER_MODEL = 'users.UserInfo'

# SECURE_SSL_REDIRECT = True


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),



    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated', ),



    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '10000000/day',
        'user': '200/minute'
    },
    'EXCEPTION_HANDLER': 'ABCHospital.exceptions.custom_exception_handler',
    'DEFAULT_PAGINATION_CLASS': 'ABCHospital.paginators.GeneralPagination',
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    # 'PAGE_SIZE': 8,

}


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'ar'

TIME_ZONE = 'Africa/Cairo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


LANGUAGES = [
    ('en', _('English')),
    ('ar', _('Arabic')),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/


STATIC_URL = '/static/'
STATIC_ROOT = Path(BASE_DIR).joinpath('staticfiles')
STATICFILES_DIRS = (Path(BASE_DIR).joinpath('static'),)
# Directory where uploaded media is saved.
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

if DEBUG:
    MEDIA_URL = '/media/'
else:
    MEDIA_URL = f'https://support.telasttechnologies.com:8001/media/'


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


DRF_NESTED_MULTIPART_PARSER = {
	"separator": "bracket",
	"raise_duplicate": True,
	"assign_duplicate": False,
	# # output of parser is converted to querydict 
	# # if is set to False, dict python is returned
	"querydict": False,
}


FCM_DJANGO_SETTINGS = {
    "FCM_SERVER_KEY": "AAAA53naCmc:APA91bE1EGCKJVG2bb2FehjXbmxIq2ie44zzAdzjKF28hlWspODzp4hL5NqER6SKdcHax_HBL6QYo9QXKFuYbzVxQz9ako7VKqfQ4g7T7Xdk4sdKWfkdQFyktpMcs5GWzIe9qnzG3ATq",
    # default: _('FCM Django')
    # true if you want to have only one active device per registered user at a time
    # default: False
    "ONE_DEVICE_PER_USER": False,
    # devices to which notifications cannot be sent,
    # are deleted upon receiving error response from FCM
    # default: False
    "DELETE_INACTIVE_DEVICES": True,
    # Transform create of an existing Device (based on registration id) into
    # an update. See the section
    # "Update of device with duplicate registration ID" for more details.
    "UPDATE_ON_DUPLICATE_REG_ID": True,
}


SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'token': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
        },
    },
    'DEFAULT_AUTO_SCHEMA_CLASS': 'drf_yasg_examples.SwaggerAutoSchema',
}

ZENDAR_API_KEY = "08c71a7362b462c59fb1fffdd006ca42c362478a"
ZENDAR_ACCOUNT = "1708203506c4ca4238a0b923820dcc509a6f75849b65d11df2dbc2f"