# Generated by Django 4.2.7 on 2023-12-13 00:18

import prcore.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurvayTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('flag', models.BooleanField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('group', models.CharField(choices=[('rate', 'Rate'), ('yes_no', 'YES/NO')], max_length=50)),
                ('answer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.PositiveIntegerField()),
                ('admission_no', models.CharField(max_length=255)),
                ('enter_date', models.DateTimeField()),
                ('doctor', models.CharField(max_length=255)),
                ('patient', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255, validators=[prcore.validators.validate_phone])),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('flag', models.BooleanField()),
                ('answers', models.ManyToManyField(to='pr.surveyanswer')),
                ('info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pr.surveyinfo')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SurvayQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('group', models.CharField(choices=[('rate', 'Rate'), ('yes_no', 'YES/NO')], max_length=50)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pr.survaytemplate')),
            ],
        ),
    ]
