# Generated by Django 4.2.7 on 2023-12-13 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SurvayQuestion',
            new_name='SurveyQuestion',
        ),
        migrations.RenameModel(
            old_name='SurvayTemplate',
            new_name='SurveyTemplate',
        ),
    ]
