# Generated by Django 4.2.7 on 2023-12-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0002_rename_survayquestion_surveyquestion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyquestion',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='surveytemplate',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='surveyinfo',
            name='age',
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_type',
            field=models.CharField(choices=[('in_person', 'In Person'), ('call', 'Call')], default='in_person', max_length=50),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='surveytemplate',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
