# Generated by Django 4.2.7 on 2023-12-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0004_alter_surveyquestion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
