# Generated by Django 4.2.9 on 2024-02-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0009_rename_admission_no_surveyinfo_medical_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRSiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfied_message', models.TextField(verbose_name='default satisfied message')),
                ('unsatisfied_message', models.TextField(verbose_name='default unsatisfied message')),
            ],
            options={
                'verbose_name': 'PR Site Config',
            },
        ),
        migrations.AddField(
            model_name='surveyinfo',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyinfo',
            name='satisfied',
            field=models.BooleanField(default=True),
        ),
    ]
