# Generated by Django 4.2.7 on 2024-02-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0015_rename_weight_surveyanswer_periority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyquestion',
            name='weight',
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='periority',
            field=models.PositiveIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1, verbose_name='periority'),
        ),
    ]
