# Generated by Django 4.2.7 on 2024-02-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0017_auto_20240218_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyanswer',
            name='answer',
            field=models.PositiveIntegerField(),
        ),
    ]
