# Generated by Django 4.2.9 on 2024-02-28 08:39

from django.db import migrations


def edit_old_data_in_survey(apps, schema_editor):
    SurveyQuestion = apps.get_model('pr', 'SurveyQuestion')
    Survey = apps.get_model('pr', 'Survey')
    
    outpatient = Survey.objects.filter(flag=True)    
    for survey in outpatient:
        answers = survey.answers.all()
        for answer in answers:
            question = answer.question
            q = SurveyQuestion.objects.filter(question=question, template__flag=True)
            if q.exists():
                q = q.get()
                answer.category = q.category
                answer.periority = q.periority
                answer.save()
            
    inpatient = Survey.objects.filter(flag=False)
    for survey in inpatient:
        answers = survey.answers.all()
        for answer in answers:
            question = answer.question
            q = SurveyQuestion.objects.filter(question=question, template__flag=False)
            if q.exists():
                q = q.get()
                answer.category = q.category
                answer.periority = q.periority
                answer.save()
    
    
class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0018_alter_surveyanswer_answer'),
    ]

    operations = [
        migrations.RunPython(edit_old_data_in_survey),
    ]
