# Generated by Django 4.2.9 on 2024-03-07 05:22

from django.db import migrations

def update_groups(apps, schema_editor):
    SurveyQuestion = apps.get_model('pr', 'SurveyQuestion')
    SurveyQuestion.objects.filter(category='doctor').update(category='medical')
    SurveyQuestion.objects.filter(category='receptionist').update(category='admission_office')
    SurveyQuestion.objects.filter(category='kitchen').update(category='food_and_beverages')
    SurveyQuestion.objects.filter(category='care').update(category='hospitality')


class Migration(migrations.Migration):

    dependencies = [
        ('pr', '0021_update_old_groups'),
    ]

    operations = [
        migrations.RunPython(update_groups),
    ]
