# Generated by Django 4.2.7 on 2023-11-11 18:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import ticket.models.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTicket',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('building', models.CharField(choices=[('Building 1', 'Building 1'), ('Building 2', 'Building 2'), ('Stores', 'Stores')], max_length=10)),
                ('floor', models.CharField(choices=[('Basement', 'Basement'), ('Ground', 'Ground'), ('Admin', 'Admin'), ('El-Hegaz', 'El-Hegaz'), ('Lebanon-Sqaure', 'Lebanon-Sqaure'), ('Floor 1', 'Floor 1'), ('Floor 2', 'Floor 2'), ('Floor 3', 'Floor 3'), ('Floor 4', 'Floor 4'), ('Floor 5', 'Floor 5'), ('Floor 6', 'Floor 6'), ('Floor 7', 'Floor 7')], max_length=20)),
                ('discribtion', models.TextField()),
                ('status', models.CharField(choices=[('on hold', 'on hold'), ('in progress', 'in progress'), ('complete', 'complete')], default='on hold', max_length=12)),
                ('extension', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1000)])),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[ticket.models.validators.validate_phone])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical ticket',
                'verbose_name_plural': 'historical tickets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ImportExportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='title')),
                ('files', models.FileField(blank=True, null=True, upload_to='tickets/import-export/%Y/%m/%d')),
                ('url_file', models.URLField(blank=True, max_length=2000, null=True)),
                ('is_import', models.BooleanField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='ISSUESType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='NoteComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='NoteMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(blank=True, null=True, upload_to='notes/%Y/%m/%d')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('building', models.CharField(choices=[('Building 1', 'Building 1'), ('Building 2', 'Building 2'), ('Stores', 'Stores')], max_length=10)),
                ('floor', models.CharField(choices=[('Basement', 'Basement'), ('Ground', 'Ground'), ('Admin', 'Admin'), ('El-Hegaz', 'El-Hegaz'), ('Lebanon-Sqaure', 'Lebanon-Sqaure'), ('Floor 1', 'Floor 1'), ('Floor 2', 'Floor 2'), ('Floor 3', 'Floor 3'), ('Floor 4', 'Floor 4'), ('Floor 5', 'Floor 5'), ('Floor 6', 'Floor 6'), ('Floor 7', 'Floor 7')], max_length=20)),
                ('discribtion', models.TextField()),
                ('status', models.CharField(choices=[('on hold', 'on hold'), ('in progress', 'in progress'), ('complete', 'complete')], default='on hold', max_length=12)),
                ('extension', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1000)])),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[ticket.models.validators.validate_phone])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='TicketMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tickets/tickets-attachments/%Y/%m/%d')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_ticket', to='ticket.ticket')),
            ],
        ),
    ]
