# Generated by Django 4.2.7 on 2023-11-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='building',
            field=models.CharField(choices=[('building_1', 'Building 1'), ('building_2', 'Building 2'), ('building_3', 'Building 3')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalticket',
            name='floor',
            field=models.CharField(choices=[('basement', 'Basement'), ('ground', 'Ground'), ('admin', 'Admin'), ('el_hegaz', 'El-Hegaz'), ('lebanon_sqaure', 'Lebanon-Sqaure'), ('floor_1', 'Floor 1'), ('floor_2', 'Floor 2'), ('floor_3', 'Floor 3'), ('floor_4', 'Floor 4'), ('floor_5', 'Floor 5'), ('floor_6', 'Floor 6'), ('floor_7', 'Floor 7')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalticket',
            name='status',
            field=models.CharField(choices=[('on_hold', 'On Hold'), ('in_progress', 'In Progress'), ('complete', 'Complete')], default='on_hold', max_length=12),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='building',
            field=models.CharField(choices=[('building_1', 'Building 1'), ('building_2', 'Building 2'), ('building_3', 'Building 3')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='floor',
            field=models.CharField(choices=[('basement', 'Basement'), ('ground', 'Ground'), ('admin', 'Admin'), ('el_hegaz', 'El-Hegaz'), ('lebanon_sqaure', 'Lebanon-Sqaure'), ('floor_1', 'Floor 1'), ('floor_2', 'Floor 2'), ('floor_3', 'Floor 3'), ('floor_4', 'Floor 4'), ('floor_5', 'Floor 5'), ('floor_6', 'Floor 6'), ('floor_7', 'Floor 7')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('on_hold', 'On Hold'), ('in_progress', 'In Progress'), ('complete', 'Complete')], default='on_hold', max_length=12),
        ),
    ]
