# Generated by Django 4.2.7 on 2023-12-23 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_alter_historicalticket_building_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalticket',
            old_name='discribtion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='discribtion',
            new_name='description',
        ),
    ]
