# Generated by Django 5.0.6 on 2024-07-26 11:11

from django.db import migrations

def set_default_close_time(apps, schema_editor):
    Ticket = apps.get_model('ticket', 'Ticket')
    HistoricalTicket = apps.get_model('ticket', 'HistoricalTicket')

    for ticket in Ticket.objects.filter(status="complete", closed_at__isnull=True):
        ticket.closed_at = HistoricalTicket.objects.filter(id=ticket.id).first().history_date
        ticket.save()

class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_historicalticket_closed_at_ticket_closed_at_and_more'),
    ]

    operations = [
        migrations.RunPython(set_default_close_time, migrations.RunPython.noop),
    ]
