# Generated by Django 5.0.6 on 2024-08-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_default_close_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='floor',
            field=models.CharField(choices=[('basement', 'Basement'), ('ground', 'Ground'), ('admin', 'Admin'), ('el_hegaz', 'El-Hegaz'), ('lebanon_sqaure', 'Lebanon-Sqaure'), ('floor_1', 'Floor 1'), ('floor_2', 'Floor 2'), ('floor_3', 'Floor 3'), ('floor_4', 'Floor 4'), ('floor_5', 'Floor 5'), ('floor_6', 'Floor 6'), ('floor_7', 'Floor 7'), ('laboratory', 'Laboratory'), ('endoscopy', 'Endoscopy'), ('or', 'OR')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalticket',
            name='status',
            field=models.CharField(choices=[('on_hold', 'On Hold'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('closed', 'Closed')], default='on_hold', max_length=12),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='floor',
            field=models.CharField(choices=[('basement', 'Basement'), ('ground', 'Ground'), ('admin', 'Admin'), ('el_hegaz', 'El-Hegaz'), ('lebanon_sqaure', 'Lebanon-Sqaure'), ('floor_1', 'Floor 1'), ('floor_2', 'Floor 2'), ('floor_3', 'Floor 3'), ('floor_4', 'Floor 4'), ('floor_5', 'Floor 5'), ('floor_6', 'Floor 6'), ('floor_7', 'Floor 7'), ('laboratory', 'Laboratory'), ('endoscopy', 'Endoscopy'), ('or', 'OR')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('on_hold', 'On Hold'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('closed', 'Closed')], default='on_hold', max_length=12),
        ),
    ]
