# Generated by Django 5.0.9 on 2025-12-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_alter_historicalticket_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
    ]
