# Generated by Django 5.0.9 on 2026-07-27 23:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_tickettransfer'),
        ('users', '0003_department_sla_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='archived_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='due date'),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=10, verbose_name='priority'),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='room',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='room'),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='sla_breach_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='SLA deadline'),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='sla_warning_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='ticket_number',
            field=models.CharField(blank=True, db_index=True, help_text='Human-friendly reference, e.g. TKT-001234.', max_length=20, null=True, verbose_name='ticket number'),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='updated_at'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='due date'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=10, verbose_name='priority'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='ticket',
            name='room',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='room'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_breach_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='SLA deadline'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sla_warning_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(blank=True, help_text='Human-friendly reference, e.g. TKT-001234.', max_length=20, null=True, unique=True, verbose_name='ticket number'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='updated_at'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', '-created_at'], name='ticket_tick_status_4da6c0_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['department', 'status'], name='ticket_tick_departm_b4ab18_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_to', 'status'], name='ticket_tick_assigne_263a1d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['priority', 'status'], name='ticket_tick_priorit_dfce6c_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['sla_deadline'], name='ticket_tick_sla_dea_1aa185_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['is_archived'], name='ticket_tick_is_arch_131f18_idx'),
        ),
    ]
