# Generated by Django 5.0.9 on 2026-08-11 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_alter_note_options_note_pinned_notereaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='building',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalticket',
            name='floor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='building',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='floor',
            field=models.CharField(max_length=50),
        ),
    ]
