# Generated by Django 5.0.9 on 2026-08-11 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0014_alter_historicalticket_building_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketcomment',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='tickets/chat/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='attachment_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='attachment_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='kind',
            field=models.CharField(choices=[('text', 'text'), ('image', 'image'), ('audio', 'audio'), ('file', 'file')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='ticket.ticketcomment'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='ticketcomment',
            index=models.Index(fields=['ticket', '-id'], name='ticket_tick_ticket__2d1dff_idx'),
        ),
    ]
